### ISSUE TITLE
When growing radical in terminal amide, this one gets to cis

### ISSUE THREAD

**Issue by danielSoler93** [carlesperez94/frag_pele#11]
# Error

When growing radical in terminal amide, this one gets to cis

# Solution

Check PELE rotatable bond. Otherwise, analise why it happens

# Files

Private

**Comment by carlesperez94** [comment]
# Solution

After solving the issue #17, when selecting the hydrogen properly you can choose between cis or trans position of the amide. Now all the terminals have both positions.
