### ISSUE TITLE
Growing a fragment between two cores

### ISSUE THREAD

**Issue by aparente-nurix** [carlesperez94/frag_pele#38]
Hi,

This tool looks really interesting! Before digging too heavily into this, I'm wondering if its feasible to grow fragments connecting two different cores.

Thanks!

**Comment by danielSoler93** [comment]
Hi, 

First of all, thanks for the interest. Right now FragPELE can grow from one core any type of fragment. For instance, in your specific case scenario from the initial core1 you could grow the linker+core2. You could potentially do that with several linkers+core2 and check which of them gives you a better energy and a better binding mode. 

For your information, this python package is a  wrapper on top of a commercial software call PELE++. Please send a message to pelesupport@nostrumbiodiscovery.com if you are interested to do a pilot project with the software.


Feel free to close the issue.

Thanks

Dani

**Comment by aparente-nurix** [comment]
Thanks!
