### ISSUE TITLE
Consecutive growing unavailable

### ISSUE THREAD

**Issue by carlesperez94** [carlesperez94/frag_pele#46]
Consecutive growings are interrupted due to a bug when searching the folders. We need to check it.

**Comment by carlesperez94** [comment]
[p38_test.tar.gz](https://github.com/carlesperez94/frag_pele/files/4503093/p38_test.tar.gz)
Folder to reproduce the error

**Comment by danielSoler93** [comment]
Sequential growing being messed up for folder movement on last version. Inclusion of tests for restart, sequential and flags.  Everything fixed on PR #47
