### ISSUE TITLE
Frag pele 

### ISSUE THREAD

**Issue by croshong** [carlesperez94/frag_pele#67]
Hi My name is Jong hui Hong

The tool 'Frag-pele' seems to be really useful for our purpose.

While we are trying to install Frag-pele in our server, it seems to require  pre-installed schrodinger and PELE software.

At this point, I have a question

1. For schrodinger, Can we use free version Maestro which can be downloaded at schrodinger web site ?

2. For PELE, we are trying to download and install it but only webserver for PELE not standalone package is available.
   Can you please tell me how can we obtain PELE software?

Thanks 

Best regards
Jong hui

**Comment by carlesperez94** [comment]
This message was answered via direct message.
